language:
  - node_js
  - ruby
node_js:
  - 12
rvm:
  - 2.5.5
sudo: required
services:
  - xvfd
  - mongodb
env:
  global:
    - SERVER_URL=172.17.0.1:3000
    - LAUNCH_URL=172.17.0.1:3001

before_install:
  - rvm install 2.5.5
  - rvm use 2.5.5

install:
  - gem install bundler
  - npm install yarn
  - bundle install
  - cd $TRAVIS_BUILD_DIR/frontend/
  - yarn install
  - cd $TRAVIS_BUILD_DIR/
before_script:
  - export RAILS_ENV=test
  - export HOST_URL="localhost"
  - export notification_email="sender@gmail.com"
  - rails s &
  - cd $TRAVIS_BUILD_DIR/frontend/
  - export PORT=3001 ; yarn start &
  - until curl -s http://localhost:3000; do sleep 5; done
  - until curl -s http://localhost:3001; do sleep 5; done
  - cd $TRAVIS_BUILD_DIR/
script:
  - bundle exec rails test
  - cd $TRAVIS_BUILD_DIR/frontend/
  - npx codeceptjs run --steps
